stages:
  - build

build:
  stage: build
  script:
    # installing the tools
    - apt-get update -qq
    - apt-get install -y -qq cmake ninja-build
  
    # installing TexLive related packages (~~basic schema)
    - apt-get -y -qq --no-install-recommends install  texlive-base texlive-binaries texlive-latex-base texlive-lang-european
  
    # somehow TexLive depends on xzdec too, so install it
    - apt-get install xzdec
  
    # initialize TexLive package dependencies and folder hierarchies if needed
    - tlmgr init-usertree
    - tlmgr install  $(cat latex_packages.txt)
  
    - mkdir build
    - cd build
    - cmake -G Ninja ..
    - ninja
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    paths:
    - build/release
