stages:
  - build
#   - deploy

build:
  stage: build
  cache:
    paths:
      - binaries/
      - build/
  script:
    - chmod +x .gitlab-ci/install_cache.sh
    
    - ./.gitlab-ci/install_cache.sh
    - source .gitlab-ci/export_paths.sh
    
    - if [ ! -d build ]; then mkdir build; fi
    - cd build
    - cmake -G Ninja ..
    - ninja
    
  artifacts:
    paths:
    - $(pwd)/build/release

# deploy:
#   stage: deploy
#   dependencies:
#     - build
#   only:
#     - cmake_support
#   script:
#     - apt-get install -y -qq lftp
#     - cd build
#     - echo $CAESAR_URL.$CAESAR_USER
#     - ls -la ~
#     #- lftp -e "mirror -Rev release/ /afs/elte.hu/user/s/steakhal/home/" -u $CAESAR_USER,$CAESAR_PASW $CAESAR_URL
